#defaults: &default
#  adapter: sqlite3
#  encoding: utf8
#
#development:
#  <<: *default
#  database: db/development.sqlite3
#
#test:
#  <<: *default
#  database: db/development.sqlite3_test
#
#production:
#  <<: *default
#  database: db/development.sqlite3_production

development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000