defaults: &default
  adapter: sqlite3
  encoding: utf8

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/development.sqlite3_test



production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000