# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31bb964f2cf7cf12b64adb04002c67fa9b516cc97f930447774725d0d79ca45d42520bcc9e3dccc745e5618deb6c3cbb3d96cd5fcb1ded66e69289a04b119d29

test:
  secret_key_base: dbb24933a9d2298b658f0f6df7a5b26040519dbe325e8d8c4dd05d83c2055dbd2ac464ab8b9cd4a37c84186746439e85dd4b39e186c59b2d5904808f3d47cd68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
